name: CI - Actions trigger

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          # Actions: https://github.com/archongum/Actions/tree/image_migration
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACTIONS_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/archongum/Actions/actions/workflows/image_migration.yml/dispatches \
            -d '{"ref":"image_migration"}'
