name: Build Alluxio

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Alluxio checkout
      uses: actions/checkout@v3
      with:
        repository: archongum/alluxio
        fetch-depth: 2
        ref: v2.7.3-hdfs-2.7.3
    - name: This repo checkout
      uses: actions/checkout@v3
      with:
        path: _Actions
        fetch-depth: 2

    - name: Set up Env
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: maven build
      run: |
        # maven build
        mvn clean install \
        -pl underfs/hdfs \
        -pl shaded \
        -Dmaven.javadoc.skip=true \
        -DskipTests \
        -Dlicense.skip=true \
        -Dcheckstyle.skip=true \
        -Dfindbugs.skip=true \
        -Pufs-hadoop-2 \
        -Dufs.hadoop.version=2.7.3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Upload to docker hub
      env:
        IMAGE_NAME: dockergum/alluxio:hdfs-2.7.3
      run: |
        # show size
        du -sh ./*
        # upload
        docker build . --file ./_Actions/Dockerfile --tag $IMAGE_NAME
        docker push $IMAGE_NAME
