name: Build HiBench

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: HiBench checkout
      uses: actions/checkout@v3
      with:
        repository: Intel-bigdata/HiBench
        fetch-depth: 2
        ref: v7.1.1
    - name: This repo checkout
      uses: actions/checkout@v3
      with:
        path: _Actions
        fetch-depth: 2

    - name: Set up Env
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: maven build
      run: |
        # maven build
        mvn -Phadoopbench -Dmodules -Pmicro -Dhadoop=2.7 -Dhive=1.2 clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Upload to docker hub
      env:
        IMAGE_NAME: dockergum/hibench:7.1.1
      run: |
        # show size
        du -sh ./*
        # upload
        docker build . --file ./_Actions/Dockerfile --tag $IMAGE_NAME
        docker push $IMAGE_NAME
