name: CI - Docker

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Push to Registry
        env:
          LIVY_VERSION: 0.8.0-snapshot
          IMAGE_NAME: archongum/livy:0.8.0-snapshot-spark-3.3.2
        run: |
          # show size
          du -sh ./*
          # build
          docker build . -f Dockerfile --tag $IMAGE_NAME --build-arg LIVY_VERSION=$LIVY_VERSION
          docker tag $IMAGE_NAME ${{ secrets.ALIYUN_REGISTRY_URL }}/$IMAGE_NAME
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME
          docker push ${{ secrets.ALIYUN_REGISTRY_URL }}/$IMAGE_NAME
