name: Build HiBench

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Config git
      run: |
        git config --global user.name  "CI/CD - archongum"
        git config --global user.email "qq349074225@live.com"

    - name: maven build
      user: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      run: |
        git clone --depth 1 https://github.com/Intel-bigdata/HiBench
        cd ./HiBench
        # maven build
        mvn -Phadoopbench -Dhadoop=2.7 -Dhive=1.2 clean package

    - name: Upload presto-jdbc-zeppelin
      env:
        BRANCH_NAME: presto-jdbc/zeppelin_jar
      run: |
        # upload
        ls -Rl ./
