name: CI - Docker

on: ["push"]

jobs:
  build:
    strategy:
      matrix:
        spark: [3.1.3, 3.2.4, 3.3.2]
        hadoop: [2, 3]
        include:
        - spark: 3.4.1
          hadoop: 3
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Push to Registry
        env:
          IMAGE_NAME: archongum/spark-thriftserver:${{ matrix.spark }}-hadoop${{ matrix.hadoop }}
        run: |
          # show size
          du -sh ./*
          # build
          docker build . -f Dockerfile --tag $IMAGE_NAME --build-arg SPARK_VERSION=${{ matrix.spark }} --build-arg HADOOP_VERSION=${{ matrix.hadoop }}
          docker tag $IMAGE_NAME ${{ secrets.ALIYUN_REGISTRY_URL }}/$IMAGE_NAME
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME
          docker push ${{ secrets.ALIYUN_REGISTRY_URL }}/$IMAGE_NAME
