name: CI - Docker

on: ["push"]

jobs:
  build:
    strategy:
      matrix:
        spark: [3.1.3, 3.2.3, 3.3.2]
        hadoop: [2, 3]
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Push to Aliyun Registry
        env:
          IMAGE_NAME: registry.cn-guangzhou.aliyuncs.com/archongum/spark-thriftserver:${{ matrix.spark }}-hadoop${{ matrix.hadoop }}
        run: |
          # show size
          du -sh ./*
          # build
          docker build . -f Dockerfile --tag $IMAGE_NAME --build-arg SPARK_VERSION=${{ matrix.spark }} --build-arg HADOOP_VERSION=${{ matrix.hadoop }}
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME